apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev1 
  name: dev1-role 
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["get", "watch", "list", "create", "delete"]
