apiVersion: v1
kind: Pod
metadata:
  name: count 
spec:
  containers:
  - image: nhm0819/count 
    name: html-generator
    volumeMounts:
    - mountPath: /var/htdocs 
      name: html
  - image: httpd
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    emptyDir:
      sizeLimit: 500Mi
