apiVersion: v1
kind: Pod
metadata:
  name: envar-secret
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: username 
      valueFrom:
        secretKeyRef:
          name: user-pass
          key: username
    - name: password 
      valueFrom:
        secretKeyRef:
          name: user-pass
          key: password 
