apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: "2023-03-23T09:28:45Z"
  name: limit-mem-cpu-per-container
  namespace: limitrange-demo
  resourceVersion: "731461"
  uid: e0ac140e-d8d7-4553-861d-77628b6c494f
spec:
  limits:
  - default:
      cpu: 700m
      memory: 900Mi
    defaultRequest:
      cpu: 110m
      memory: 111Mi
    max:
      cpu: 800m
      memory: 1Gi
    min:
      cpu: 100m
      memory: 99Mi
    type: Container
