apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: test
  template:
    metadata:
      labels:
        tier: test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
